import { render } from "@testing-library/react";
import { mockIsBuildTime } from "@src/clients/web.framework/__mocks__/vendor.mock";
import ErrorBoundary from "@src/components/errors/boundary/error.boundary.component";
import ErrorDisplay from "@src/components/errors/display/error.display.component";
import routes from "@src/config/routes";
import Events from "@src/events/events";
import Page, { getStaticProps } from "@src/pages/404";
import mockCheckCall from "@src/tests/fixtures/mock.component.call";
import mockStaticProps from "@src/utils/__mocks__/page.props.static.mock";
import getPageProps from "@src/utils/page.props.static";

jest.mock("@src/hooks/router");

jest.mock("@src/utils/page.props.static");

jest.mock("@src/clients/web.framework/vendor");

jest.mock("@src/components/errors/boundary/error.boundary.component", () =>
  require("@fixtures/react/parent").createComponent("ErrorBoundary")
);

jest.mock("@src/components/errors/display/error.display.component", () =>
  require("@fixtures/react/parent").createComponent("ErrorDisplay")
);

describe("getStaticProps", () => {
  it("should be the return value of pagePropsGenerator", () => {
    expect(getStaticProps).toBe(mockStaticProps);
  });

  it("should be generated by a correct call to pagePropsGenerator", () => {
    expect(getPageProps).toBeCalledTimes(1);
    expect(getPageProps).toBeCalledWith({ pageKey: "default" });
  });
});

describe("404", () => {
  const arrange = () => {
    render(<Page />);
  };

  beforeEach(() => jest.clearAllMocks());

  describe("when rendered at build time", () => {
    beforeEach(() => {
      mockIsBuildTime.mockReturnValue(true);

      arrange();
    });

    it("should NOT call the ErrorBoundary component", () => {
      expect(ErrorBoundary).toBeCalledTimes(0);
    });

    it("should NOT call the ErrorDisplay component", () => {
      expect(ErrorDisplay).toBeCalledTimes(0);
    });
  });

  describe("when rendered at run time", () => {
    beforeEach(() => {
      mockIsBuildTime.mockReturnValue(false);

      arrange();
    });

    it("should call the ErrorBoundary correctly", () => {
      expect(ErrorBoundary).toBeCalledTimes(1);
      mockCheckCall(
        ErrorBoundary,
        {
          route: routes.home,
          eventDefinition: Events.General.Error,
        },
        0,
        ["stateReset"]
      );
    });

    it("should call the ErrorDisplay correctly", () => {
      expect(ErrorDisplay).toBeCalledTimes(1);
      mockCheckCall(ErrorDisplay, { errorKey: "404" }, 0, ["resetError"]);
    });
  });
});
