import { render } from "@testing-library/react";
import AboutContainer from "@src/components/about/about.container";
import ErrorBoundaryContainer from "@src/components/errors/boundary/error.boundary.container";
import routes from "@src/config/routes";
import Events from "@src/events/events";
import Page, { getServerSideProps } from "@src/pages/about";
import mockCheckCall from "@src/tests/fixtures/mock.component.call";
import mockServerSideProps from "@src/utils/__mocks__/page.props.server.side.mock";
import getPageProps from "@src/utils/page.props.server.side";

jest.mock("@src/utils/page.props.server.side");

jest.mock("@src/components/errors/boundary/error.boundary.container", () =>
  require("@fixtures/react/parent").createComponent("ErrorBoundary")
);

jest.mock("@src/components/about/about.container", () =>
  require("@fixtures/react/parent").createComponent("AboutContainer")
);

describe("getStaticProps", () => {
  it("should be the return value of pagePropsGenerator", () => {
    expect(getServerSideProps).toBe(mockServerSideProps);
  });

  it("should be generated by a correct call to pagePropsGenerator", () => {
    expect(getPageProps).toBeCalledTimes(1);
    expect(getPageProps).toBeCalledWith({
      pageKey: "home",
      translations: ["about"],
    });
  });
});

describe("About", () => {
  const arrange = () => {
    render(<Page />);
  };

  beforeEach(() => jest.clearAllMocks());

  describe("when rendered", () => {
    beforeEach(() => arrange());

    it("should call the ErrorBoundary component correctly", () => {
      expect(ErrorBoundaryContainer).toBeCalledTimes(1);
      mockCheckCall(
        ErrorBoundaryContainer,
        {
          route: routes.home,
          eventDefinition: Events.General.Error,
        },
        0,
        ["stateReset"]
      );
    });

    it("should call the Splash component", () => {
      expect(AboutContainer).toBeCalledTimes(1);
      mockCheckCall(AboutContainer, {});
    });
  });
});
