import * as react from "@testing-library/react";
import routes from "@src/config/routes";
import checkMockCall from "@src/fixtures/mocks/mock.component.call";
import Page, { getServerSideProps } from "@src/pages/index";
import {
  mockServerSideProps,
  mockUtilities,
} from "@src/vendors/integrations/web.framework/__mocks__/vendor.ssr.mock";
import Events from "@src/web/analytics/collection/events/definitions";
import SplashContainer from "@src/web/content/splash/components/splash.container";
import ErrorBoundaryContainer from "@src/web/ui/errors/components/boundary/error.boundary.container";

jest.mock("@src/vendors/integrations/web.framework/vendor.ssr");

jest.mock(
  "@src/web/ui/errors/components/boundary/error.boundary.container",
  () => require("@fixtures/react/parent").createComponent("ErrorBoundary")
);

jest.mock("@src/web/content/splash/components/splash.container", () =>
  require("@fixtures/react/parent").createComponent("SplashContainer")
);

describe("getServerSideProps", () => {
  it("should be the return value of serverSideProps", () => {
    expect(getServerSideProps).toBe(mockServerSideProps);
  });

  it("should be generated by a correct call to serverSideProps", () => {
    expect(mockUtilities.serverSideProps).toBeCalledTimes(1);
    expect(mockUtilities.serverSideProps).toBeCalledWith({
      pageKey: "home",
      translations: ["splash"],
    });
  });
});

describe("Splash", () => {
  const arrange = () => {
    react.render(<Page />);
  };

  beforeEach(() => jest.clearAllMocks());

  describe("when rendered", () => {
    beforeEach(() => arrange());

    it("should call the ErrorBoundary component correctly", () => {
      expect(ErrorBoundaryContainer).toBeCalledTimes(1);
      checkMockCall(
        ErrorBoundaryContainer,
        {
          route: routes.home,
          eventDefinition: Events.General.Error,
        },
        0,
        ["stateReset"]
      );
    });

    it("should call the Splash component", () => {
      expect(SplashContainer).toBeCalledTimes(1);
      checkMockCall(SplashContainer, {});
    });
  });
});
