---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-jsonschema
        name: check-github-workflow-push-schema
        files: "^\\.github/config/workflows/workflow-push.json$"
        args:
          - "--schemafile"
          - ".github/config/schemas/workflows/workflow-push.json"
        stages: [commit]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.2.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args:
          - "--trailing-comma=es5"
        stages: [commit]
  - repo: https://github.com/cicd-tools-org/pre-commit.git
    rev: 0.2.0
    hooks:
      - id: format-shell
        args:
          - "-w"
          - "--indent=2"
          - "-ci"
          - "-sr"
      - id: format-toml
      - id: lint-github-workflow
      - id: lint-markdown
        args:
          - "-c"
          - ".markdownlint.yml"
      - id: lint-shell
        args:
          - "--color=always"
          - "--source-path=SCRIPTDIR"
          - "--exclude=SC2317"
          - "-x"
      - id: security-credentials
      - id: spelling-commit-message
      - id: spelling-markdown
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - "-c"
          - "./.yamllint.yml"
        stages: [commit]
