import { render } from "@testing-library/react";
import ReportPage from "@src/components/reports/lastfm/common/report.page/report.page";
import PlayCountByArtistReport from "@src/components/reports/lastfm/playcount.artists/playcount.artists.container";
import routes from "@src/config/routes";
import FourOhFour from "@src/pages/404";
import Page, {
  getServerSideProps,
} from "@src/pages/reports/lastfm/playCountByArtist";
import mockCheckCall from "@src/tests/fixtures/mock.component.call";
import mockServerSideProps from "@src/utils/__mocks__/page.props.server.side.mock";
import getPageProps from "@src/utils/page.props.server.side";

jest.mock("@src/utils/page.props.server.side");

jest.mock("@src/components/reports/lastfm/common/report.page/report.page", () =>
  require("@fixtures/react/parent").createComponent("ReportPage")
);

jest.mock(
  "@src/components/reports/lastfm/playcount.artists/playcount.artists.container",
  () =>
    require("@fixtures/react/parent").createComponent("PlayCountByArtistReport")
);

jest.mock("@src/pages/404", () =>
  require("@fixtures/react/parent").createComponent("FourOhFour")
);

describe("getStaticProps", () => {
  it("should be the return value of pagePropsGenerator", () => {
    expect(getServerSideProps).toBe(mockServerSideProps);
  });

  it("should be generated by a correct call to pagePropsGenerator", () => {
    expect(getPageProps).toBeCalledTimes(1);
    expect(getPageProps).toBeCalledWith({
      pageKey: "lastfm",
      translations: ["lastfm", "sunburst"],
    });
  });
});

describe(routes.reports.lastfm.playCountByArtist, () => {
  beforeEach(() => jest.clearAllMocks());

  const arrange = () => {
    render(<Page />);
  };

  describe("when rendered", () => {
    beforeEach(() => {
      arrange();
    });

    it("should call the ReportPage correctly", () => {
      expect(ReportPage).toBeCalledTimes(1);
      mockCheckCall(
        ReportPage,
        {
          ReportContainer: PlayCountByArtistReport,
          NoUserComponent: FourOhFour,
        },
        0,
        ["stateReset"]
      );
    });
  });
});
