const env = {
  BASEURL: "BASEURL" as const,
  FLAG_GROUPS_HASH: "FLAG_GROUPS_HASH" as const,
  NEXT_PUBLIC_FLAG_ENVIRONMENT: "NEXT_PUBLIC_FLAG_ENVIRONMENT" as const,
  SMOKE_TEST_ALL_ACCESS_TOKEN: "SMOKE_TEST_ALL_ACCESS_TOKEN" as const,
  SMOKE_TEST_NO_ACCESS_TOKEN: "SMOKE_TEST_NO_ACCESS_TOKEN" as const,
};

export default env;
