const env = {
  BASEURL: "BASEURL" as const,
  FLAG_ENABLED_REPORTS: "FLAG_ENABLED_REPORTS" as const,
  FLAG_GROUPS_HASH: "FLAG_GROUPS_HASH" as const,
  SMOKE_TEST_ALL_ACCESS_TOKEN: "SMOKE_TEST_ALL_ACCESS_TOKEN" as const,
  SMOKE_TEST_NO_ACCESS_TOKEN: "SMOKE_TEST_NO_ACCESS_TOKEN" as const,
  LASTFM_TEST_ACCOUNT_NO_LISTENS: "LASTFM_TEST_ACCOUNT_NO_LISTENS" as const,
  LASTFM_TEST_ACCOUNT_WITH_LISTENS: "LASTFM_TEST_ACCOUNT_WITH_LISTENS" as const,
};

export default env;
