export enum config {
  BASEURL = "BASEURL",
  FLAG_ENABLED_REPORTS = "FLAG_ENABLED_REPORTS",
  FLAG_GROUPS_HASH = "FLAG_GROUPS_HASH",
  SMOKE_TEST_ALL_ACCESS_TOKEN = "SMOKE_TEST_ALL_ACCESS_TOKEN",
  SMOKE_TEST_NO_ACCESS_TOKEN = "SMOKE_TEST_NO_ACCESS_TOKEN",
  LASTFM_TEST_ACCOUNT_NO_LISTENS = "LASTFM_TEST_ACCOUNT_NO_LISTENS",
  LASTFM_TEST_ACCOUNT_WITH_LISTENS = "LASTFM_TEST_ACCOUNT_WITH_LISTENS",
}

export const getValueOf = (key: config) => {
  return Cypress.env(config[key]);
};
